name: CI

on:
  push:
    paths-ignore:
      - '.gitattributes'
      - '.github/*'
      - '.gitignore'
      - 'README.md'
  pull_request:
    paths-ignore:
      - '.gitattributes'
      - '.github/*'
      - '.gitignore'
      - 'README.md'

jobs:
  Build:
    name: Build (${{ matrix.configuration}}${{ matrix.config.Configuration_2 }})
    runs-on: windows-2019
    strategy:
      fail-fast: false
      matrix:
        Configuration: [Release, Debug]
        config:
          - {SDK: orangebox}
          - {SDK: bms, Configuration_2: ' BMS'}
          - {SDK: sdk2013, Configuration_2: ' 2013'}
          - {SDK: episode1, Configuration_2: ' OE'}
    steps:
      - name: Checkout SPT
        uses: actions/checkout@v3
      - name: Checkout submodules
        run: git submodule update --init -j $env:NUMBER_OF_PROCESSORS SPTLib SDK\${{ matrix.config.SDK }}
      - uses: microsoft/setup-msbuild@v1.1
      - name: Build
        run: msbuild -m -nologo -p:Configuration="${{ matrix.Configuration }}${{ matrix.config.Configuration_2 }}" spt.sln
      - name: Get SPT DLL name
        id: get_spt_filename
        run: |
          $spt_filename = (Get-Item "${{ matrix.Configuration }}${{ matrix.config.Configuration_2 }}\spt*.dll").BaseName
          echo "spt_filename=$spt_filename" >> $env:GITHUB_OUTPUT
      - uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.Configuration }}${{ matrix.config.Configuration_2 }} - ${{ steps.get_spt_filename.outputs.spt_filename }}
          path: ${{ matrix.Configuration }}${{ matrix.config.Configuration_2 }}\${{ steps.get_spt_filename.outputs.spt_filename }}.dll
          if-no-files-found: error
