name: CI

on:
  push:
    paths-ignore: 'README.md'
  pull_request:
    paths-ignore: 'README.md'

jobs:
  Build:
    runs-on: windows-2019
    strategy:
      fail-fast: false
      matrix:
        Configuration: [Debug, Debug BMS, Debug 2013, Debug OE, Release, Release BMS, Release 2013, Release OE]
        include:
          - Configuration: Debug
            SDK: orangebox
          - Configuration: Debug BMS
            SDK: bms
          - Configuration: Debug 2013
            SDK: sdk2013
          - Configuration: Debug OE
            SDK: episode1
          - Configuration: Release
            SDK: orangebox
          - Configuration: Release BMS
            SDK: bms
          - Configuration: Release 2013
            SDK: sdk2013
          - Configuration: Release OE
            SDK: episode1
    steps:
      - name: Checkout SPT
        uses: actions/checkout@v3
      - name: Checkout submodules
        run: git submodule update --init -j $env:NUMBER_OF_PROCESSORS SPTLib SDK\${{ matrix.SDK }}
      - uses: microsoft/setup-msbuild@v1
      - name: Build
        run: msbuild /m /nologo /p:Configuration="${{ matrix.Configuration }}" spt.sln
      - name: Get SPT DLL name
        id: get_spt_filename
        run: |
          $spt_filename = (Get-Item "${{ matrix.Configuration }}\spt*.dll").BaseName
          echo "::set-output name=spt_filename::$spt_filename"
      - uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.Configuration }} - ${{ steps.get_spt_filename.outputs.spt_filename }}
          path: ${{ matrix.Configuration }}\${{ steps.get_spt_filename.outputs.spt_filename }}.dll
          if-no-files-found: error

  Format:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - name: Format
        run: python run-clang-format.py --clang-format-executable clang-format-11 --recursive spt
